version: '3.7'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./docker-volumes/caddy/data/:/tls:ro

  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: on-failure

  caddy:
    image: caddy:2.6-alpine
    restart: on-failure
    volumes:
      - ./docker-volumes/caddy/data:/data
      - ./docker-volumes/caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
