version: '3.7'

services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
  mailhog:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:8025:8025
