version: '3.7'

services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:7-alpine
    restart: on-failure
    ports:
      - 127.0.0.1:6379:6379

  minio:
    image: minio/minio:latest
    restart: on-failure
    entrypoint: sh
    command: -c '/opt/bin/minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: ${RESOURCES_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${RESOURCES_S3_SECRET_KEY}
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    volumes:
      - ./docker-volumes/minio:/data

  # Only for development
  mailhog:
    image: mailhog/mailhog
