version: '3.7'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    restart: on-failure
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - 1025:1025
      - 8025:8025

  minio:
    image: minio/minio:latest
    restart: on-failure
    entrypoint: sh
    command: -c '/opt/bin/minio server /data'
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./docker-volumes/minio:/data
