name: Backend (API) tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test-backend-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Create test private key for signing alerts
        run: ssh-keygen -m PKCS8 -t ecdsa -f $(pwd)/test-key

      - name: Start PostgreSQL Docker container for testing
        run: docker-compose -f docker-compose-test-api.yml up -d

      - name: Run backend API tests
        run: pnpm run test:api
        env:
          BASE_URL: http://example.com
          VERIFIER_EMAIL: ifrc@example.com
          PRIVATE_KEY_FILENAME: test-key
          TLS_DIRECTORY: ./

      - uses: actions/upload-artifact@v4
        with:
          name: 'coverage-api'
          path: './coverage-api'

