name: Frontend (React) tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run frontend component tests
        run: npm run test:frontend
