name: Test Frontend components

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      - name: Run frontend component tests
        run: npm run test:frontend
